server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/api/v1/accounts/**

        - id: money-transfer-service
          uri: lb://money-transfer-service
          predicates:
            - Path=/api/v1/transfers/**

        - id: transaction-history-service
          uri: lb://transaction-history-service
          predicates:
            - Path=/api/v1/history/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
