spring.application.name=play-with-spring-boot


# # H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# # JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# # H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.probes.enabled=true
management.endpoint.health.probes.add-additional-paths=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.endpoint.health.group.liveness.include=livenessState,ping
management.endpoint.health.group.readiness.include=readinessState,db,customReadiness

# cassandra
cassandra.contact-points=localhost
cassandra.port=9042
cassandra.keyspace=backup


# tomcat thread pool configuration
server.tomcat.threads.max=200
