server:
  port: 8484

spring:
  application:
    name: transaction-history-service
  cassandra:
    contact-points: localhost:9042,localhost:9043
    local-datacenter: datacenter1
    keyspace-name: mts
    schema-action: none
    request:
      consistency: LOCAL_QUORUM
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      group-id: history-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.npci.event.TransferEvent

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
